### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by TaotianZhufang** [AbCooly/nonebot_plugin_wolf_kill#1]
数组0怎么用上了啊，六个人0-6都可以投，还有能不能显示谁是几号啊，都是乱的

**Comment by AbCooly** [comment]
因为投0是弃票。号数是参加顺序，要管理员权限开始游戏才会改群卡片为号数。我后续加几个艾特进去应该会好点

**Comment by TaotianZhufang** [comment]
谢谢，我没有注意到提示，不过我不是很懂您说的“改群卡片为号数”这句话的意思。但是我在群聊中测试的时候，我记录过每个人的参加顺序，到头来发现顺序与号数对不上。另外，您写的指令的捕获有一些小问题，对于bot使用了全局指令开头必须加上'/'，然后指令就变成了‘//参加狼人杀’之类的，在执行‘//守护 3’之类的要带上数字的指令会报错（我自己修改了一下就好了）。另外，执行这些指令的时候可以选0，于是就错乱了。以至于bot发出消息：‘0号已死亡’，这时候号数出现混乱，我也不是很懂这个机制。会附上聊天截图。这一场有很多不对劲的地方
![LH52_A24B@ 8CJD_T_9C4KE](https://user-images.githubusercontent.com/111833184/190301075-7c974a97-0a8f-42f1-949c-3229b37ec558.jpg)

> 因为投0是弃票。号数是参加顺序，要管理员权限开始游戏才会改群卡片为号数。我后续加几个艾特进去应该会好点

**Comment by AbCooly** [comment]
好的 已经修复了
