### ISSUE TITLE
[建议]可否将on_command中的/去掉

### ISSUE THREAD

**Issue by bywhite0** [AbCooly/nonebot_plugin_wolf_kill#2]
因为我的命令前缀配置为
```env
COMMAND_START=["/"]
```
在使用时就必须多加一个`/`，故提出这条Issue，希望作者可以参考。

例如把
https://github.com/AbCooly/nonebot_plugin_wolf_kill/blob/043a8dca04faad65a75a99cc7f1bfd38a8853a79/__init__.py#L56
改成
```python
zd = on_command("自定义")
```
然后在所有处理函数中的`command`改为nonebot命令前缀配置+该命令的形式

例如把
https://github.com/AbCooly/nonebot_plugin_wolf_kill/blob/043a8dca04faad65a75a99cc7f1bfd38a8853a79/__init__.py#L61
改成
```python
from nonebot import get_driver # 先import
driver = get_driver()

command = driver.config.COMMAND_START[0] + "自定义"
```

**Comment by bywhite0** [comment]
最后那段其实我没有测试过（）

**Comment by AbCooly** [comment]
好的。 现在改成了统一用“/”前缀
