### ISSUE TITLE
bug,驱逐人跟投票最多不匹配

### ISSUE THREAD

**Issue by PilotSherlock** [AbCooly/nonebot_plugin_wolf_kill#5]
第二轮投票之后驱逐的人不对，
![image](https://user-images.githubusercontent.com/42969918/202848232-c4a776d7-5ef3-47cd-aa36-3731c7dd1211.png)
比如这个投最多的是6号，最后把3号驱逐了，甚至都没有人给3号投过

**Comment by AbCooly** [comment]
更新了新版本 再试试
