### ISSUE TITLE
大佬，为什么安装命令用完没有文件？

### ISSUE THREAD

**Issue by ghost** [AbCooly/nonebot_plugin_wolf_kill#8]
ModuleNotFoundError: No module named 'nonebot_plugin_wolf_kill'
![image](https://user-images.githubusercontent.com/110887475/207491429-89db3b29-e849-4627-81ef-988c3dcdeb4a.png)

**Comment by AbCooly** [comment]
我忘更新了 刚上传

**Comment by AbCooly** [comment]
你直接拷贝文件吧

**Comment by ghost** [comment]
请问是直接把文件放入data目录里吗？我不太会&nbsp;


大梦一场空
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月14日(星期三) 中午12:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AbCooly/nonebot_plugin_wolf_kill] 大佬，为什么安装命令用完没有文件？ (Issue #8)





 
你直接拷贝文件吧

**Comment by AbCooly** [comment]
弄好了 你卸载重装试试

**Comment by AbCooly** [comment]
> 请问是直接把文件放入data目录里吗？我不太会&nbsp; 大梦一场空 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年12月14日(星期三) 中午12:42 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [AbCooly/nonebot_plugin_wolf_kill] 大佬，为什么安装命令用完没有文件？ (Issue #8) 你直接拷贝文件吧 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

一般放到plugins里

**Comment by ghost** [comment]
> 弄好了 你卸载重装试试
还是不行，我用的nonebot商店里的安装命令：nb plugin install nonebot-plugin-wolf-kill
让后nb run 有个报错：[ERROR] nonebot | Failed to import "nonebot_plugin_wolf_kill"
ModuleNotFoundError: No module named 'nonebot_plugin_wolf_kill'

**Comment by AbCooly** [comment]
先卸载 nb plugin uninstall nonebot-plugin-wolf-kill
再安装 nb plugin install nonebot-plugin-wolf-kill
 然后 pip show nonebot-plugin-wolf-kill 看看是不是2.0.4版本
